admin <- tribble(
    ~institution, ~title, ~detail,
    "University of Oklahoma", "Director of Online MS Finance Program", "Directed High Graduation Rate (>78%) Online Degree with approximately 150 students",
    "University of Oklahoma", "Director of Online MS Finance Program", "Attained CFA Institute University Affiliation Program status",
    "University of Oklahoma", "Director of Online MS Finance Program", "Developed Marketing Strategy for Implementation by 3rd Party Provider",
    "University of Oklahoma", "Director of Online MS Finance Program", "Created Streamlined Admissions Process for Automatic and Accelerated Admission Decisions",
    "University of Oklahoma", "Director of Online MS Finance Program", "Modified and Updated Program Offerings for Learner Flexibility",
    "University of Oklahoma", "Director of Online MS Finance Program", "Worked with Instructional Design Team to Deliver Consistent Course Structures",
    "University of Oklahoma", "Director of Online MS Finance Program", "Created and Delivered 1st Asynchronous Offering",
    "University of Oklahoma", "Assistant Director of Finance Division", "Assisted Director (Chair) with Managing 5th Largest Unit in OU system - Approximately 1050 Majors",
    "University of Oklahoma", "Assistant Director of Finance Division", "Managed Staff, Recruited Students and Faculty, Developed and Managed Programs, Engaged in Strategic Planning",
    "University of Oklahoma", "Assistant Director of Finance Division", "Directed Initiative to Restructure Undergraduate Curriculum to Incorporate Certificate Structure",
    "University of Oklahoma", "Assistant Director of Finance Division", "Modified Teaching Schedules, Worked with Development Office on 7-Figure Fund-Raising Gifts",
    "University of Oklahoma", "Co-Program Director for Global Business Experience in Arezzo Italy", 
    "Managed Schedule for Academic and Cultural Activities",
    "University of Oklahoma", "Co-Program Director for Global Business Experience in Arezzo Italy", 
    "Taught Undergraduate Principles of Finance",
    "University of Oklahoma", "Co-Program Director for Global Business Experience in Arezzo Italy", 
    "Guided Students on Cultural Trips to Florence and Rome",
    "Estonian Business School", "Finance Area Head", "Managed Program Across Multi-Nation Campuses, Created Nano Degree, Recruited Faculty, Engaged in Strategic Planning",
    "Rutgers University","Multi-Year Finance Area Head", "Led Online MBA Initiative, Managed Teaching Schedule, Recruited Faculty",
    "Rutgers University","Multi-Year Finance Area Head", "Engaged in Strategic Planning, Worked with Donors on 5-Figure Scholarship Gifts"
    
)

ltWork <- tribble(
    ~institution, ~startMonth, ~startYear, ~endMonth, ~endYear, ~where, ~detail,
    "SUNY - Empire", "August", 2025, "Present", NA, "Saratoga Springs, NY", "Associate Professor Finance",
    "SUNY - Empire", "August", 2025, "Present", NA, "Saratoga Springs, NY",
    "COURSES TAUGHT --- Financial Management, Investment Analysis, Mergers and Acquisitions",
    "University of Oklahoma", "January", 2021, "July", 2024, "Norman, OK", "Professor of Finance", 
    "University of Oklahoma", "January", 2021, "July", 2024, "Norman, OK", "Director, MS Finance Program",
    "University of Oklahoma", "January", 2021, "July", 2024, "Norman, OK", "Assistant Director, Finance Division",
    "University of Oklahoma", "January", 2021, "July", 2024, "Norman, OK", 
    "COURSES TAUGHT --- Principles of Finance (UG; Online, F2F, Study Abroad/MS), Investments (MS), Risk Management (MS) and Student Investment Fund ($1.3MM AUM)",
    "Estonian Business School", "September", 2018, "December", 2020, "Tallinn, Estonia", "Professor of Finance (2019-2020)",	
    "Estonian Business School", "September", 2018, "December", 2020, "Tallinn, Estonia", "Finance Area Head (2019-2020)",
    "Estonian Business School", "September", 2018, "December", 2020, "Tallinn, Estonia", 
    "Creator of Quantamentals Nano Degree (2020)",
    "Estonian Business School", "September", 2018, "December", 2020, "Tallinn, Estonia",
    "COURSES TAUGHT --- Intro and Intermediate Corporate Finance at Grad/UG Levels at both Tallinn and Helsinki Branches; 
    Grad Only Levels: Data Analysis, Introduction to R, Financial Statement Analysis", 
    "Estonian Business School", "September", 2018, "December", 2020, "Tallinn, Estonia", "Visiting Professor (2018)",
    "Hanken School of Economics", "September", 2016, "July", 2020, "Helsinki, Finland", "Visting Professor (2018-2020)",
    "Hanken School of Economics", "September", 2016, "July", 2020, "Helsinki, Finland", 
    "COURSES TAUGHT --- Introduction to Market Analytics Using R - fully asynchronous online",
    "Hanken School of Economics", "September", 2016, "July", 2020, "Helsinki, Finland", 
    "Distinguished Visiting Research Fellow (2017)",
    "Hanken School of Economics", "September", 2016, "July", 2020, "Helsinki, Finland", 
    "Fulbright Distinguished Chair in Business and Economics (2016)",
    "Rutgers University", "July", 1997, "Present", NA, "Camden, NJ", "Professor Emeritus (2018 - Present)",
    "Rutgers University", "July", 1997, "Present", NA, "Camden, NJ", "Associate Professor (2003 - 2018)",
    "Rutgers University", "July", 1997, "Present", NA, "Camden, NJ", "Assistant Professor (1997 - 2003)",
    "Rutgers University", "July", 1997, "Present", NA, "Camden, NJ", 
    "Director, Financial and Legal Research Institute (2009 - 2010)",
    "Rutgers University", "July", 1997, "Present", NA, "Camden, NJ", 
    "COURSES TAUGHT --- Portfolio Implementation/Equity Trading using TraderEx, 
    Advanced Corporate Valuation using Bloomberg, Equity Investments, Securities and Investments, 
    Statistical Financial Modeling using open source software and data, Investments and Portfolio Management, 
    Advanced Portfolio Management (Simulated Student Managed Fund), Principles of Finance (Fully Asynchronous Online), 
    Financial Management (Fully Asynchronous online and traditional in-class), Applications of Financial Management, 
    and Financial Management and Policy",
    "Middlesex University", "January", 2015, "December", 2016, "London, England", "Visiting Research Professor",
    "Fairleigh Dickinson University", "September", 1995, "June", 1997, "Madison, NJ", "Assistant Professor",
    "Fairleigh Dickinson University", "September", 1995, "June", 1997, "Madison, NJ", "COURSES TAUGHT --- Capital Market Theory, Investments, Portfolio Management, Corporate Seminar, Co-Op Mentor",
    "Lousiana State University", "September", 1992, "August", 1995, "Baton Rouge, LA", "Instructor (1994 - 1995)",
    "Lousiana State University", "September", 1992, "August", 1995, "Baton Rouge, LA", "Research Assistant (1992 - 1995)",
    "Millsaps College", "September", 1990, "May", 1991, "Jackson, MS", "Research Assistant"
    
)

stWork <- tribble(
    ~institution, ~startMonth, ~startYear, ~endMonth, ~endYear, ~where, ~detail,
    "Estonian Business School", "October", 2024, "Present", NA, "Tallinn, Estonia", "Visiting Professor",
    "ZHAW Banking, Finance, Real Estate", "July", 2024, "Present", NA, "Winterthur, Switzerland", "International Lecturer",
    "Turku School of Economics", "January", 2013, "February", 2013, "Turku, Finland", "Visiting Professor",
    "Lappeenranta University of Technology", "January", 2007, "February", 2007, "Lappeenranta, Finland", "Visiting Professor"
    
)

edu <- tribble(
    ~inst, ~degree, ~startYear, ~endYear, ~where, ~detail,
    "Lousiana State University","PhD., Finance",1991,1995,"Baton Rouge, LA",NA,
    "Millsaps College","MBA, Finance",1988,1991,"Jackson, MS",NA,
    "Lousiana State University","B.S., Biochemistry",1981,1985,"Baton Rouge, LA",NA
)


certifications <- tribble(
    ~certBody, ~accomplishment, ~year, ~where, ~detail,
    "Insitute of Business Appraisers","Certified Business Appraiser",2005,"","Passed Exam",
    "Professional Risk Managers' International Association","Professional Risk Manager (PRM)",2003,"","Awarded PRM Designation",
    "Global Association of Risk Professionals","Certified Financial Risk Manager (FRM)",1999,"","Awarded FRM Designation",
    "CFA Institute","Chartered Financial Analyst (CFA)",1997,"","Awarded CFA Deisgnation, Charter #24928"
)


honorsGrants <- tribble(
    ~honorGrant, ~grantor, ~where, ~year, ~detail,
    "William J. Alley-Rayonier International Business Scholars Program","University of Oklahoma", "Norman, OK", 2024, NA,
    "Faculty Travel Assistance Program Award Recipient, Vice President for Research and Partnerships Office","University of Oklahoma",
    "Norman, OK", 2023, NA,
    "William J. Alley-Rayonier International Business Scholars Program","University of Oklahoma", "Norman, OK", 2023, NA,
    "William J. Alley-Rayonier International Business Scholars Program","University of Oklahoma", "Norman, OK", 2022, NA,
    "Best Lecturer at Master's Level","Estonian Business School","Tallinn, Estonia",2020,NA,
    "Hanken Distinguished Research Fellow Grant", "Hanken School of Economics", "Helsinki, Finland",2017,NA,
    "Fulbright Distinguished Research Grant","Hanken School of Economics","Helsinki, Finland",2016,NA,
    "School of Business Teaching Excellence Award", "Rutgers University", "Camden, NJ",2016,NA,
    "Summer Research Grant","Rutgers University","Camden, NJ",2014,NA,
    "Summer Research Grant","Rutgers University", "Camden, NJ",2013,NA,
    "School of Business Research Excellence Award","Rutgers University", "Camden, NJ",2012,NA,
    "Invited Speaker Grant", "Council of Institutional Investors","Los Angeles, CA",2005,NA,
    "Provost's Award for Teaching Excellence", "Rutgers University","Camden, NJ",2003,NA,
    "School of Business Teaching Excellence Award","Rutgers University", "Camden, NJ",2002,NA,
    "Student Advisor of the Year Award", "Rutgers University", "Camden, NJ",2001,NA,
    "Student Advisor of the Year Award", "Rutgers University", "Camden, NJ",2000,NA,
    "School of Business Teaching Excellence Award","Rutgers University", "Camden, NJ",2000,NA,
    "Invited Speaker Grant","Finnish Portfolio Academy","Helsinki, Finland",1999,NA,
    "Doctoral Student Symposium Speaker","Swedish School of Economics and Business Administration","Helsinki, Finland",1998,NA,
    "CBOT Research Foundation Grant","Chicago Board of Trade","Chicago, IL",1997,NA,
    "Visiting Scholar Grant","Office of Comptroller of Currency, Risk Analysis Division","Washington, DC",1997,NA,
    "Summer Grant-In-Aid Recipient","Fairleigh Dickinson University","Madison, NJ",1996,NA,
    "Research Grant Recipient","Foundation for Finnish Capital Market Research","Helsinki, Finland",1995,NA,
    "FMA Doctoral Student Seminar Representative", "Financial Management Association","St. Louis, MO",1994,NA,
    "Travel Grant Recipient","Deutsche Vereinigung fur Finanzanalyse und Anlageberatung","Frankfurt, Germany",1994,NA,
    "Financial Mangement Association National Honor Society","Millsaps College","Jackson, MS",1991,NA
)


publications <- tribble(
    ~articleTitle, ~authors, ~journal, ~year,
    "The Market Ecosystem in the Age of Algorithms: Analysis of Trading Dynamics and Market Quality",
    "with Andrei Nikiforov and Sergey Osmekhin",
    "Journal of Economics and Finance, https://doi.org/10.1007/s12197-024-09702-w",
    "2025",
    "Time-variation of Dual-class Premia",
    "with Mika Vaihekoski",
    "Nordic Journal of Business, v71, n1, 26-50",
    "2022",
    "Modeling Flash Crash Behavior in a Stock Market Using Multivariate Hawkes Processes",
    "with G. Geoffrey Booth and Bill Shi",
    "Journal of Economic Interaction and Coordination",
    "2021",
    "The Efficacy of Life Insurance Company General Account Equity Asset Allocations: A Safety-First Perspective Using Vine Copulas",
    "with G. Geoffrey Booth and Ryan Timmer",
    "Annals of Actuarial Science, v12 n2, 372-390, Available at https://doi.org/10.1017/S17484995170002642018",
    "2018",
    "Style Migration In Europe",
    "with Vesa Puttonen and Jussi Mikkonen",
    "European Financial Management, v22 n5, 797-816. Available at https://doi.org/10.1111/eufm.12083",
    "2016",
    "Communication Technology and Exchanging of Financial Assets: A Historical Perspective",
    "with G. Geoffrey Booth and Elizabeth Booth",
    "Business and Economic Research, v4 n2, 308-322. Available at https://doi.org/10.5296/ber.v4i2.6643",
    "2014",
    "Intraday Periododicity in Algorithmic Trading",
    "with Andrei Nikiforov",
    "Journal of International Financial Markets, Institutions, and Money, v30, 196-204. Available at http://dx.doi.org/10.1016/j.intfin.2014.03.001",
    "2014",
    "Is There Price Discovery in Equity Options",
    "with Neil Pearson and Dmitriy Muravyev",
    "Journal of Financial Economics, v107 n2, 259-283. Available at http://dx.doi.org/10.1016/j.jfineco.2012.09.003",
    "2013",
    "Profitability of Pairs Trading Strategy in an Illiquid Market with Multiple Share Classes",
    "with Mika Vaihekoski",
    "Journal of International Financial Markets, Institutions, and Money, v22, n5, 1188-1201. Available at https://doi.org/10.1016/j.intfin.2012.06.002",
    "2012",
    "Saving for Retirement: The Effects of Fund Assortment Size and Investor Knowledge of Asset Allocation Strategies",
    "with Maureen Morrin, Susan Broniarczyk and J. Jeffery Inman",
    "Journal of Consumer Affairs, v42 n2, 206-222. Available at https://doi.org/10.111/j.1745-66-6.2008.00105.x",
    "2008",
    "The Role of Growth in Long Term Investment Returns",
    "with Walter Neely and David Michayluk",
    "Journal of Applied Business Research, v21 n1, 93-104. Available at https://doi.org/10.19030/jabr.v21i1.1503",
    "2005",
    "CEO Incentives, Cash Flow, and Investment",
    "with Gene Pilotte and Sherrie Buchenroth",
    "Financial Management, v33 n2, 51-70. Available at https://www.jstor.org/stable/3666158",
    "2004",
    "The Role of REITs in Asset Allocation",
    "with G. Geoffrey Booth",
    "Finance,v23, 109-124",
    "2002",
    "Extreme-Value and Margin Setting with and without Price Limits",
    "sole authored",
    "Quarterly Review of Economics and Finance, v41, 365-385. Available at https://doi.org/10.1016/S1062-9769(00)00083-1",
    "2001",
    "Testing the Contrarian Investment Strategy Using Holding Period Returns",
    "with Julie Dahlquist",
    "Managerial Finance, v26 n6, 16-22. Available at https://doi.org/10.1108/03074350010766701",
    "2000",
    "Reply to Note on Earnings and Stock Returns: Evidence from Germany",
    "with G. Geoffrey Booth and Otto Loistl",
    "The European Accounting Review, v8 n3, 656-568. Available at https://doi.org/10.1080/096381899335943",
    "1999",
    "Big Players and the Russian Ruble: Explaining Volatility Dynamics",
    "with Roger Koppl",
    "Managerial Finance, v25 n1, 49-63. Available at https://doi.org/10.1108/03074359910765858",
    "1999",
    "Setting NYSE Circuit Breaker Triggers",
    "with G. Geoffrey Booth",
    "Journal of Financial Services Research, v13 n3, 187-204. Available at http://dx.doi.org/https://doi.org/10.1023/A:1008074725372",
    "1998",
    "Price Discovery in German Stock and Futures Markets",
    "with G. Geoffrey Booth and Otto Loistl",
    "Managerial Finance, v24 n4, 3-18. Available at https://doi.org/10.1108/03074359810765444",
    "1998",
    "The Behavior of Extreme Values in German Stock Index Futures: An Application to Intradaily Margin Setting",
    "with G. Geoffrey Booth",
    "European Journal of Operational Research, v104, 393-402. Available at https://doi.org/10.1016/S0377-2217(97)00014-3",
    "1998",
    "Earnings and Stock Returns: Evidence from Germany",
    "with G. Geoffrey Booth and Otto Loistl",
    "The European Accounting Review, v6 n4, 589-603. Available at https://doi.org/10.1080/09638189700000002",
    "1997",
    "Prudent Margin Levels in the Finnish Stock Index Futures Market",
    "with G. Geoffrey Booth, Teppo Martikainen and Vesa Puttonen",
    "Management Science, v43 n8, 1177-1188. Available at https://doi.org/10.1287/mnsc.43.8.1177",
    "1997"
)

pip <- tribble(
    ~articleTitle, ~authors, ~status, 
    "Algorithmic Trading and Market Quality",
    "with Sergey Osmekhin and Andrei Nikifororov",
    "Journal Resubmission",
    "The Vines of Dr. Copper",
    "with Barbara Rašiová and Peter Árendáš",
    "Conference Presentation Submission",
    "Vines in Endowment Portfolio Management",
    "with G. Geoffrey Booth and Ryan Timmer",
    "Analysis Currently Performed",
    #"Strategic Discussion and Finance Performance",
    #"with Vasiliki Athanassakou and Minna Martikainen",
    #"Analysis Currently Performed",
    "Earnings Management as a Function of Alternative Earnings",
    "with Tatiana Garanina and Mikko Ranta",
    "Prepration for Journal Submission"
    #wip,Mutual Alternatives to Hedge Funds: Market Neutral and Long / Short Funds,,with Walter Neely and Vesa Puttonen,,,,,,
    #wip,Multivariate Extreme Characteristics of Soft and Hard Commodities,,with Torun Fretheim,,,,,,
    #wip,What's in a Company Name? Sentiment or Familiarity?,,with Timo Korkamaki,,,,,,
    #wip,The Alphabet and Mutual Fund Names,,with Jan Antell and Anders Loflund,,,,,,
)

otherPubsMonos <- tribble(
    ~title, ~outlet, ~year, ~authors, 
    "The Sortino Ratio and the Generalized Pareto Distribution: An Application to Asset Allocation",
    "Wiley Handbook of Financial Engineering and Econometrics: Extreme Value Theory and its Applicaiton to Finance and Insurance: Chapter edited by Francois Longin, Wiley Publishing",
    2016,
    "with G. Geoffrey Booth",
    "The Competition of Systems for the Market for Listings",
    "Economic Law as an Economic Good, edited by Karl M. Meesen, Chapter 3, 167-185, Sellier, European Law Publishers",
    2009,
    "with Arthur Laby",
    "Bank Stock Returns, Interest Rate Changes and the Regulatory Environment: New Insights from Japan",
    "The Japanese Finance: Corporate Finance and Capital Markets in Changing Japan: 
    International Finance Review, v4, edited by J. H. Choe and T. Hiraki, Elsevier Science",
    2003,
    "with Ken Kim and Piman Lipaphayom",
    "Using SAS in Financial  and Accounting Research", 
    "Books By Users: SAS Press",
    2002,
    "with Ekkehart Boehmer and J.P. Kallunki",
    "The Relationship between Economic Freedom and Transitionary Economic Growth",
    "Economics and Transition: Conception, Status, and Prospects: 
    edited by A. Young, I. Teodorovic, P. Koveos, World Scientific Publishing Co. Ltd.",
    2002,
    "with Peter Koveos and Allan Young",
    "The Index of Economic Freedom and Economic Growth in Transition Economies", 
    "Globalization and Economic Growth, A Critical Evaluation: edited by . T. Georgakopoulos, C. Paraskevopoulos and J. Smith in, APF Press Toronto, Canada. Reprinted in Zagreb Internatioanl Reviews of Economics and Business.",
    2001,
    "with Peter Koveos and Allan Young",
    "Governance, Economic and Financial Factors Affecting Success for Transition Economies",
    "Proceeding of Rijeka Faculty of Economics: Journal of Economics and Business Chapters 7-18. 
    Reprinted as Chapter 11 in Economics and Transition: Conception, Status, and Prospects,
    edited by A. Young, I. Teodorovic, P. Koveos, World Scientific Publishing Co. Ltd.",
    2000,
    "with Peter Koveos and Allan Young",
    "Porssikriisien Todennakoisyys Kasvanut (Probability of Crises and Extreme Events)",
    "Talouselama (Finnish Economic Life)",
    1995,
    "with G. Geoffrey Booth, Teppo Martikainens and Vesa Puttonen",
    "German Stock Returns and the Information Content of DVFA Earnings",
    "Deutsche Vereinigung fur Finanzanalyse",
    1994,
    "with G. Geoffrey Booth and Otto Loistl, reprinted 1995"
)

academicPresents <- tribble(
    ~articleTitle, ~authors, ~detail,
    "More Than Meets the Eye (or Ear): Surprising Microstructure Effects of Fed Chair Nonverbal
    Cues in High-Frequency Markets", 
    "with Andrei Nikiforov",
    "3f Conference, Vilnius, August 2025",
    "Algorithmic Trading and Market Quality",
    "with Sergey Osmekhin and Andrei Nikifororov",
    "JAAF Conference, Helsinki, June 2023",
    "Modeling Flash Crash Behavior in a Stock Market using Multivariate Hawkes Processes",
    "with Fing Shi and G. Geoffrey Booth",
    "Paris Financial Management Conference, 2019; University of Latvia and Stockholm Business School, 2020",
    "Time-variation of Dual-Class Premia",
    "with Mika Vaihekoski",
    "Groningen and Vaasa Universities, 2019; Hanken School of Economics 2019",
    "Measuring and Modeling Market Risk for Life Insurance Company Assets: An Application of Extreme Value Statistics",
    "with G. Geoffrey Booth and Ryan Timmer",
    "LaBaulle, 2016; Turku and Vaasa Universities, 2016",
    "Intraday Periododicity in Algorithmic Trading",
    "with Andrei Nikiforov",
    "Multinational Finance Society Conference; Prague, 2014",
    "The Sortino Ratio and the Generalized Pareto Distribution: An Application to Asset Allocation",
    "with G. Geoffrey Booth",
    "Rutgers Statistics and Risk Managment Practitioner Seminar; New Brunswick, NJ, 2014",
    "Style Migration In Europe",
    "with Vesa Puttonen and Jussi Mikkonen",
    "FMA European Conference; Luxembourg, 2013",
    "Is There Price Discovery in Equity Options",
    "with Neil Pearson and Dmitriy Muravyev",
    "Utah Winter Finance Conference, Texas A&M, University of Illinois, University of Notre Dame, 
    Hong Kong University of Science and Technology, City University of Hong Kong, Hong Kong University, C
    hinese University fo Hong Kong University Seminars - 2011",
    "Profitability of Pairs Trading Strategy in Finland",
    "with Mika Vaihekoski",
    "Portuguese Finance Network, 2010",
    "CEO Incentives, Cash Flow, and Investment",
    "with Gene Pilotte and Sheree Buchenroth",
    "Eastern Finance Association Meeting, 2003",
    "The Index of Economic Freedom and Economic Growth in Transition Economies",
    "with Peter Koveos and Allan Young",
    "European Applied Business Research Conference, An Enterprise Odyssey: Economics and Business in the new Millennium, 2002",
    "The Relationship between Economic Freedom and Transitionary Economic Growth",
    "with Peter Koveos and Allan Young",
    "Academy of International Business/Southeast Asia and Austrailia Confernece, 2002",
    "Governance, Factors and Economic Transition: Some Additional Evidence",
    "with Peter Koveos and Allan Young",
    "4th International Conference on Enterprises in Transition; Faculty of Economics, University of Split, 2001",
    "The Relationship Between Economic Freedom and Economic Growth in Asia",
    "with Peter Koveos and Allan Young",
    "Academay of International Business/Southeast Asia and Austrailia Conference, 2002,2002",    
    "A Transaction-Level Investigation of the Day-of-the-Week Trading Patterns",
    "with S. G. Badrinath and S. Chakravarty",
    "Financial Management Association Meeting, Orlando, 1999; 
    26th Annual European Finance Association Meeting, Helsinki, Finland, 2000",
    "Bank Stock Returns, Interest Rate Changes and the Regulatory Environment: New Insights from Japan",
    "with Ken Kim and Piman Limaphayom",
    "Midwest Finance Association Meeting, 1999; Southwest Finance Association Meeting, 1999; 
    2nd Annual Washington Area Finance Association Meeting, 1998; 
    5th Annual Conference of the Multinational Finance Society, Helsinki, 1998",
    "The Role of Growth in Long Term Investment Returns",
    "with Walter Neely and Dave Michayluk",
    "EFMA-FMA European Conference, 1998",
    "REIT Returns, Probability of Large Losses, and Asset Allocation",
    "with G. Geoffrey Booth",
    "15th Annual Meeting of the French Finance Association; 5th Annual Confernce of the Multinational Finance Society-Helsinki, 1999",
    "Taxonomy of Central and Eastern European and Former USSR Transition Economies",
    "with Allan Young and Roger Koppl",
    "5th Annual Conference of the Multinational Finance Society, 1998",
    "Interest Rates and Bank Stock Returns: A Comparison between Japanase and U.S. Banks",
    "with Ken Kim and Piman Limpaphayom",
    "Annual Southern Finance Association Meeting, 1997",
    "Setting NYSE Circuit Breaker Triggers",
    "with G. Geoffrey Booth",
    "Syracuse University's Finance Seminar Series; 14th Annual meeting of the French Finance Association; 
    Vanderbilt University's 'Ten Years Since the Crash' Conference; 
    Rutgers University-Camden Campus Capital Markets Seminar; 
    Visiting Scholar Program at the Office of the Comptroller of the Currency, 1997",
    "Big Players and the Russian Ruble: Explaining Volatility Dynamics",
    "with Roger Koppl",
    "4th Annual Conference of the Multinational Finance Society; Fairleigh Dickinson University Faculty Development Seminar,
    1997",
    "Price Discovery in German Stock and Futures Markets",
    "with G. Geoffrey Booth and Otto Loistl",
    "Financial Management Association Meeting, 1996",
    "Growth of Reasonable Price (GARP): Another Look at the Book-to-Market and Earnings-to-Price Puzzle
    with a Special Emphasis on Growth",
    "with David Michayluk and Walter Neely",
    "Annual Southwestern Finance Association Meeting; Financial Management Association Meeting, 1996",
    "The Behavior of Extreme Values in German Stock Index Futures: 
    An Application to Intradaily Margin Setting",
    "with G. Geoffrey Booth",
    "Annual Financial Management Association Meeting, 1995",
    "Prudent Margin Levels in the Finnish Stock Index Futures Market",
    "with G. Geoffrey Booth, Teppo Martikainen and Vesa Puttonen",
    "2nd Annual Conference on Multinational Finance Issues, 1995; Annual Financial Association Meeting, 1996",
    "Do Electronic Trading Systems Completely Dominate Floor Trading Systems in Information Processing Capability?
    - Evidence from Germany", 
    "with G. Geoffrey Booth and Otto Loistl",
    "1st Annual Conference on Multinational Financial Issues, 1994",
    "Price/Earnings Ratios, Growth Rates and Portfolio Returns",
    "with Walter Neely, Brian McKenna and Bill Brister",
    "13th Annual Eastern Finance Association Meeting, 1994",
    "Does Contrarian Investment Strategy Provide a Profitable Trading Rule in the U.S. Stock Market?",
    "with Julie Dahlquist",
    "Southern Finance Association Annual Meeting, 1993", 
    "The Stock Market Reaction to Green Information",
    "wtih Bill Brister",
    "18th Annual Midsouth Academy of Economics and Finance Meeting, 1991"
)

pedagogyPresents <- tribble(
    ~title, ~detail,
    "Reproducible Finance: A Potential Solution to the Paper Mill Problem",
    "Invited Speaker, Finance and Accounting Faculty, Umea, Sweden, 2024",
    "The Characteristics of an Attractive Online Offering",
    "Keynote Speaker, Digital Teaching Conference, Vaasa, Finland, 2023",
    "Bending the Cost Curve In Higher Education - What Can Finance Professors Do?",
    "Invited Panelist, Southern Finance Association Meeting, 2022",
    "So, You Want to NFT Yourself?", "Student Athlete NIL Education Session, University of OKlahoma, 2022",
    "On the Road to Experiential Learning Panel",
    "15th Annual Equity Markets Seminar, Baruch College, 2018",
    "e-Options and Finance Pedagogy", "Southern Finance Association Meeting, 2010"
)

academicDiscussions <- tribble(
    ~articleTitle, ~authors, ~detail,
    "Present-Bias and the Value of Sophistication",
    "by S. Acharya, D. Jimenez-Gomez, D. Rachinskii, and A. Rivera",
    "62nd Southern Finance Association Meeting, Key West, FL, 2022",
    "Cutting Operational Costs by Integrating Fintech into Traditional Banking Firms",
    "by L. Allen, Y Shan, Y. Tang, and A Yildirim",
    "61st Southern Finance Association Meeting, Captiva, FL, 2021",
    "Investor Sentiment and the Closed-end Fund Puzzle: Out-of-Sample Evidence",
    "by J. A. Doukas and N. T. Milonas",
    "European Financial Management Annual Meeting, Helsinki, Finland, 2003",
    "Hedging and the Use of Derivatives: Evidence from UK Non-Financial Firms",
    "by A. Judge",
    "7th Annual Conference of the Multinational Finance Society, Helsinki, Finland, 2000",
    "Nontradable Goods, Nonseperable Utility, and Global Portfolio Diversification",
    "by R. Balvers and J. Bergstrand",
    "6th Annual Conference of the Multinational Finance Society, Thesolloniki, Greece, 1999",
    "Bayesian Network Models of Porfolio Risk and Return",
    "by C.Shenoy",
    "Midwest Finance Association Meeting, Chicago, IL, 1999",
    "The Effects of Inclusion in and Removal from the S&P 500 on Stock Price and Trading Volume",
    "by C. Boyer",
    "FMA Annual Meeting, Chicago, IL, 1998",
    "Estimation of Global Systematic Risk for Securities Listed in Multiple Marktes: 
    Theoretical Development and Empirical Comparisons",
    "by M. deBoyrie, G. Ghai, S. Hamid, A. Prakash",
    "FMA Annual Meeting, Chicago, IL, 1998",
    "Information and Volatility: Evidence from Emerging Markets",
    "by N. Guner and Z. Onder",
    "5th Annual Conference of the Multinational Finance Society, Washingington, DC, 1998",
    "The Tradeoff between Skewness and Variance of Return in a Three Moment Captial Asset Pricing Model",
    "by M. Racine",
    "5th Annual Conference of the Multinational Finance Society, 1998",
    "The Development and Performance of Stock Markets in Central Europe",
    "by E. J. Zychowicz",
    "4th Annual Conference of the Multinational Finance Society, 1997",
    "Galton's Error and the Under-Representation of Systematic Risk",
    "by C. Los",
    "14th International Conference in Finance, Grenoble, France, 1997",
    "Evaluating the Probability of an Extreme Price Movement: Different Approaches",
    "by. K. Chang and F. Longin",
    "14th International Confernce in Finance, Grenoble, France, 1997",
    "How Efficient are European Stock Markets? Evidence from an Error Correction Model",
    "by. A. Ghosh",
    "Eastern Finance Association Meeting, 1996",
    "Dividend-Clientele Irrelevance and the Information Content of Dividend Changes",
    "by J. Qian et. al.",
    "Eastern Finance Association Meeting, 1996",
    "The Timing, Magnitude, and Composition of Shareholder Losses in Bankrupt Firms",
    "by D. Indro et. al.",
    "Southwestern Finance Association Meeting, San Antonio, TX, 1996",
    "Evidence of Nonlinear Relationship Between Corporate Ownership Structure and Dividend Policy",
    "by J. Wansley et. al.",
    "Financial Management Association Annual Meeting, NY, NY, 1995",
    "Duration of a Cross-Currency Swap Contract and Exchange Rate Risk Management",
    "by. D. K. Malhotra",
    "2nd Annual Confernce of Multinational Finance Issues, Philadelphia, PA, 1995",
    "Trading Volume and the Production of Information",
    "by H. M. Shefrin et. al.",
    "Financial Management Association Annual Meeting, St. Louis, MO, 1994",
    "Using the Municipal/Treasury Bond Yield Ration to Predict Investment Opportunities in Municipal Bonds",
    "by D. J. Crocket et. al.",
    "18th Annual Midsouth Academy of Economics and Finance Meeting, Monroe, LA, 1991" 
)

confCommittees <- tribble(
    ~conference, ~role, ~details,
    "Investments Track",
    "Committee Member",
    "Eastern Finance Association, 2023",
    "Investments Track",
    "Committee Member",
    "Eastern Finance Association, 2022",
    "Digital Transformation in Financial Sector, IEEE TEMS",
    "Scientific Committe",
    "Kaunus and Remote, 2021",
    "Extreme Events in Finance",
    "Co-Organizer",
    "Paris, 2014",
    "Investments Track",
    "Co-Chair",
    "Southern Finance Association, 2010 and 2011 Conferences",
    "Investments Program",
    "Committee Member",
    "Southern Finance Association, 2009",
    "International Finance Track",
    "Committee Member",
    "Financial Management Association Annual Meeting, 1996"
)

confChair <- tribble(
    ~conference, ~details,
    "Earnings Impacts and Effects",
    "JAAF Helsinki, 2023",
    "Factor Models and ESG",
    "Big Data Finance, 2021",
    "Empirical Methods in Market Microstructure",
    "61st Southern Finance Association Meeting, 2021",
    "Behavioral Issues",
    "Southern Finance Association, 2009",
    "Pricing of Interest Rate Instruments",
    "17th International Conference in Finance, French Finance Association, 2000",
    "Issues on Emerging Markets and Earnings Management",
    "7th Annual Conference of the Multinational Finance Society, 2000",
    "European Markets",
    "26th Annual European Finance Association Meeting, 1999",
    "Statistical Modeling of Asset Returns",
    "5th Annual Confernce of the Multinational Finance Society, 1998",
    "Financial System Development: A View from Eastern European Economies in Transition",
    "4th Annual Multinational Finance Society Conference, 1997",
    "Nonlinearity in Exchange Rates",
    "Financial Management Association Annual Meeting, 1995"
)

editor <- tribble(
    ~role, ~journal, ~begYear, ~endYear,
    "Associate Editor",
    "Journal of International Financial Markets, Institutions and Money",
    2008,2020
)

adHocReview <- tribble(
    ~outletName, ~outletType,
    "Journal of Economic Interaction and Coordination; Finance; Journal of Economics Business and Organization; 
    Journal of Economics and Business; 
    Journal of Business Research; Journal of International Financial Markets, Institutions & Money; 
    European Journal of Finance; Multi-Criteria Decision Analysis, Multinational Finance Journal; 
    International Review of Financial Analysis; Journal of Banking and Finance; Financial Management;
    Journal of Money, Credit and Banking; Review of Futures Markets", "Academic Journal",
    "Fundamentals of Investments, Charles Corrado and Bradford Jordan", "Textbook",
    "ETH Zurich Research Commission", "Grant Review"
)

tAndP <- tribble(
    ~task, ~school, ~year, ~role,
    "Promotion to Full Professor",
    "Colorado State University",
    2022,
    "External Reviewer for Promotion to Full Professor",
    "Promotion to Associate Professor",
    "University of Vaasa",
    2021,
    "External Reviewer of Permanent Position Promotion",
    "Appointment to Strategic Finance Professor",
    "Lapeenranta University of Technology",
    2021,
    "External Reviewer of newly created position",
    "Fintech Professor",
    "University of Vaasa",
    2019,
    "External Reviewer of Newly Created Position",
    "Promotion to Full Professor",
    "Lapeenranta University of Technology",
    2015,
    "External Reviewer of Permanent Position Promotion",
    "Promotion to Associate Professor",
    "Old Dominion University",
    2008,
    "External Reviewer for Promotion and Tenure to Associate Professor"
)

profesionalOFfices <- tribble(
    ~title, ~group, ~begYear, ~endYear,
    "Education Committee Chair","Professional Risk Managers International Association",2018,2020,
    "Board of Directors","Professional Risk Managers International Association",2002,2002,
    "Regional Director, Philadelphia Region","Professional Risk Managers International Association",2002,2002,
    "Regional Director, Philadelphia Region","Global Association of Risk Professionals",2000,2001,
    "Education Committee Co-Chair","Financial Analysts of Philadelphia (CFA Philadelphia)",1999,2000,
    "Vice President for External Affairs","Multinational Finance Society",1996,2001,
    "Business Manager","Multinational Finance Journal",1997,2001
)

academicLeader <- tribble(
    ~title, ~school, ~begYear, ~endYear,
    "Director, MSF Program",
    "University of Oklahoma","2021","2024",
    "Assistant Director, Finance Division",
    "University of Oklahoma","2021","2024",
    "Head, Finance Area",
    "Estonian Business School","2019","2020",
    "Head, Accounting and Finance Area",
    "Rutgers University", "2013","2014",
    "Coordinator, Finance Area",
    "Rutgers University","2010","2011",
    "Coordinator, Finance Area",
    "Rutgers University","2007","2008",
    "Coordinator, Finance Area",
    "Rutgers University", "2003","2005",
    "Coordinator, Finance Research Seminar Series","Rutgers University","2003","2005",
    "Coordinator, Finance Research Seminar Series","Rutgers University","1999","2000"
)

academicCommittees <- tribble(
    ~committeeName, ~institution, ~begYear, ~endYear,
    "Undergraduate Finance Curriculum Committee Taskforce","University of Oklahoma", "2024", "2024",
    "Teaching Evaluation Working Group", "University of Oklahoma", "2023", "2024",
    "Facilities Committee", "University of Oklahoma", "2023", "2024",
    "Diversity, Equity and Inclusion Strategic Planning Committee", "University of Oklahoma", "2022", "2024",
    "MSF Program Committee", "University of Oklahoma", "2021", "2024",
    "Master's Program Committee", "University of Oklahoma", "2021", "2024",
    "Finance Division Strategic Planning Committee", "University of Oklahoma", "2021", "2024",
    "Advanced Program Review Committee","University of Oklahoma", "2021", "2024",
    "Price College of Business Social Planning Committee", "University of Oklahoma", "2021", "2022",
    "Education Committee","Rutgers University","2014","2016",
    "Teaching Committee", "Rutgers University","2013","2016",
    "Undergraduate Studies Committee","Rutgers University","2010","2012",
    "Graduate Studies Committee", "Rutgers University", "2009", "2010",
    "Instructional Research and Technology Committee", "Rutgers University", "2008", "2012",
    "Personnel Evaluation Committee", "Rutgers University", "2009", "2009",
    "Undergraduate Curriculum Committee", "Rutgers University", "2009", "2009", 
    "XBRL Working Group", "CFA Institute", "2009", "2009",
    "Instructional Research and Technology Committee", "Rutgers University", "2004", "2006",
    "Corporate Governance Task Force", "CFA Institute", "2003", "2005",
    "Curriculum Committee, Co-Chair", "Rutgers University", "2003", "2005",
    "Graduate Students Committee", "Rutgers University", "2004", "2005",
    "Teaching Committee", "Rutgers University", "2003", "2004",
    "Student Admissions Committee", "Rutgers University", "2001", "2003",
    "Ethics Committee Chair", "Professional Risk Managers International Association", "2002", "2002",
    "Examination Committee", "Professional Risk Managers International Association", "2002", "2002",
    "Financial Risk Manager Ethics Committee", "Global Association of Risk Professionals", "2001", "2001",
    "Financial Risk Manager Examination Committee", "Global Association of Risk Professionals", "2001", "2001",
    "Teaching Committee", "Rutgers University", "2000", "2001",
    "Hospitality Planning Committee", "Rutgers University", "1999", "2001",
    "Appointments and Promotion Committee", "Rutgers University", "1998", "1999",
    "Collegiality Committee", "Rutgers University", "1998", "1999",
    "Education Committee", "Financial Analysts of Philadelphia (CFA Philadelphia)", "1997", "2000",
    "Course Scheduling Committee", "Rutgers University", "1997", "1998",
    "Research Release Committee", "Fairleigh Dickinson University", "1997", "1997",
    "College Educational Planning Committee", "Fairleigh Dickinson University", "1996", "1997",
    "Library Committee", "Fairleigh Dickinson University", "1996", "1997",
    "Student Life Search Committee", "Fairleigh Dickinson University", "1996", "1996",
    "World Wide Web Task Force Committee, Department Representative", "Fairleigh Dickinson University", "1995", "1997"
)

dissertationCommittees <- tribble(
    ~student, ~dissTitle, ~school, ~year, ~role,
    "Niranjan Sapkota",
    "Essays on New Blockchain-based Digital Financial Markets: Risks and Opportunities",
    "University of Vaasa", "2022",
    "Pre-Examiner and Opponent",
    "Jenny Silvfer", 
    "ESG Definitions, Measurement, Benefits and Detriments",
    "Estonian Business School", "Current", 
    "Chair",
    "Ian  Khrashchevskyi", 
    "Essay on Behavioural, Safe Havens, and Macro Decisions",
    "Stockholm Business School","2020",
    "External Examiner",
    "Junhua Jiang",
    "Essays on Financial Connectedness",
    "University of Vaasa", "2020",
    "Pre-Examiner",
    "Hoa Jiang",
    "Capital and Asset Allocation Decisions Under Policy Uncertainty: Evidence from Risk-Based Approaches",
    "University of Delaware", "2020",
    "Outside Committee Member",
    "Tuomo Haapalainen",
    "Essays on the Effects of Past Gains on Subsequent Risk Taking and Stock Returns",
    "University of Oulu", "2018",
    "Pre-Examiner",
    "Paivi Kankanranta", 
    "Essays on Household Finance and Consumptions",
    "University of Turku", "2018",
    "Committee Co-Chair",
    "Vinay Patel",
    "Price Discover in U.S. and Austrailian Stock and Options Markets",
    "Universtity of Tehcnology-Sydney", "2015",
    "External Reviewer",
    "Ryan Timmer",
    "Measuring and Modeling Market Risk for Life Insurance Company Assets: An Application of Extreme Value Statistics",
    "Michigan State University", "2015",
    "Outside Committee Member",
    "Mikael Vikstrom",
    "Essays on Option Pricing and Trading: Evaluating the Effects of Dividends and Different Time Units in the Pricing Models",
    "Hanken University", "2001",
    "External Examiner and Opponent",
    "Markku Vieru",
    "Essays on Investors' Trading Policy Around Interim Earnings Announcements in a Thinly Traded Securities Market",
    "University of Oulu", "1999",
    "External Examiner",
    "Jaako Niemela",
    "The Assessment of Capital Adequacy in Banking Sector: The BIS Ratio vs. an Alternative Multivariate Approach",
    "University of Vaasa", "1998",
    "External Examiner"
)

thesesSupervision <- tribble(
    ~student, ~thesisTitle, ~school, ~year, ~role,
    "Jared Noblitt",
    "Transaction Costs on the Ethereum Network",
    "University of Oklahoma", "2023",
    "Supervisor",
    "Seyma Avcilar",
    "Relationship between Spot Prices and Traders' Activity in Crude Oil Derivatives Market; 
    Comparison of Pre-Post Price Shock Periods",
    "Estonian Business School", "2021",
    "Supervisor",
    "Samuli Johannes Saarinen",
    "The comparative study of nowcasting over forecasting in workforce planning",
    "Estonian Business School", "2021",
    "Supervisor",
    "Julia Emilia Ervio", 
    "Performance Evaluation of Mutual Equity Funds in the Mexican Market",
    "Estonian Business School","2019",
    "Supervisor",
    "Alexander Neumuller",
    "Testing Fama-French: How Different Are U.S. Equity REIT Factors?",
    "Estonian Business School","2019",
    "Supervisor",
    "Jimit Patel", 
    "Real-Time Big Data Mining",
    "Rutgers University", "2014",
    "Co-Supervisor with M. Palis, Computer Science Department",
    "Daniel Lehmann",
    "Market Data Visualizations",
    "Rutgers University","2013",
    "Co-Supervisor with M. Palis, Computer Science Department",
    "Missy Piccione", 
    "A Regulatory Response by the Securities and Exchange Commission to the Terroist Attacks on America: Did the Registrant Repurchase Really Make a Difference?",
    "Rutgers University","2003",
    "Supervisor",
    "Caren Pocino",
    "Reg FD: Legal and Financial Impacts",
    "Rutgers University","2002",
    "Supervisor",
    "Ping-Chu Chen", 
    "A Taxonomy of Financial Risk Management",
    "Rutgers University", "2000",
    "Supervisor",
    "Diane Arachow", 
    "Contrarian Investment Strategy Criticism",
    "Rutgers University", "1999",
    "Supervisor"
)

studentMentoring <- tribble(
    ~role, ~activity, ~begYear, ~endYear, ~school,
    "Faculty Mentor", "Investment Club", "2023", "Present", "University of Oklahoma",
    "Faculty Mentor", "Houston Stock Pitch Competition","2022","2022", "University of Oklahoma",
    "Primary Contact Person", "CFA Institute University Affliation Program","2021","Present","University of Oklahoma",
    "CFA Institute CFA Scholarship Designate","CFA Examination Program", "2021","Present","University of Oklahoma",
    "Faculty Mentor","CFA Institute Global Research Challenge","2019","2020","Estonian Business School",
    "Faculty Mentor","CFA Institute Global Research Challenge","2016","2017","Hanken School of Economics",
    "Faculty Mentor","CFA Institute Global Research Challenge","2008","2009","Rutgers University",
    "Faculty Mentor","Student Finance Association","2008","2010","Rutgers University",
    "Faculty Mentor","MBA Association","2007","2008","Rutgers University ",
    "Faculty Mentor","Minding Your Bussine$$ School of Business Student Newspaper","2003","2004","Rutgers University ",
    "Faculty Instructor","BizEd program for High School Students","2005","2009","Rutgers University",
    "Faculty Mentor","Student Finance Association","1999","2005","Rutgers University ",
    "CFA Scholarship Designate","CFA Examination Program","1998","2013","Rutgers University"
)

profTraining <- tribble(
    ~role, ~activity, ~group, ~begYear, ~endYear,
    "Instructor","FRM Exam Preparation","Schweser Study Program",2002,2018,
    "Instructor","CFA Exam Preparation","Schweser Study Program",2001,2018,
    "Author and Instructor", "Various Financial Training Offerings","7city, CIFT, Cengage ",2007,2009,
    "Instructor","Financial Journalists Media Seminar","Financial Analysts of Philadelphia (CFA Philadelphia)",2002,2002,
    "Instructor","Value vs. Growth in Portfolio Managment","Conventum Mutual Fund Seminar",2001,2001,
    "Instructor","CFA Exam Preparation","Stalla Seminars",2000,2001,
    "Instructor","Growth and Investments","Portfolio Academy of Finnish Financial Analysts, LTT Research",1999,1999,
    "Instructor","CFA Exam Preparation","Post-Graduate University Program IRAM-DVFA",1999,2000,
    "Instructor", "Using the Internet for Investment Research","Financial Analysts of Philadelphia (CFA Philadelphia)",1998,1998,
    "Instructor", "So You Want to Get a Finance Degree?","Fairleigh Dickinson University Undergraduate Open House",1995,1995,
    "Instructor", "Investments After Landing a 'Real' Job - Engineering Council Seminar","Louisiana State University",1995,1995
)

mediaInterviews <- tribble(
    ~modality, ~topic, ~outlet, ~year,
    "TV Appearance","Consumer Report 401(k) Contribution","myFoxPhilly-Philadelpia Fox Affiliate",2009,
    "TV Appearance","In Focus' program - 2008 Financial Crisis: 30 minute one-on-one interview/discussion","myPhl17",2008,
    "TV Appearance","Stock Market Discussion","NBC10 - Philadelphia NBC Affiliate",NA,
    "TV Appearance","Stock Market Discussion","WB17 - Philadlephia Warner Brothers Affiliate",NA,
    "TV Appearance","Stock Market Discussion","6ABC - WABC Philadelphia ABC Affiliate",NA,
    "Radio","Stock Market Discussion","KYW-AM 1060",NA,
    "Radio","Stock Market Discussion","WOBM - Morning Radio at the New Jersey Shore",NA,
    "Radio","Stock Market Discussion","New Jersey 101.5",NA,
    "Print","Stock Market Discussion","Courier Post - South Jersey's Newspaper",NA,
    "Print","Stock Market Discussion","The Philadelphia Inquirer",NA,
    "Print","Stock Market Discussion","AM Best",NA,
    "Online Interview","Stock Market Discussion","YAHOO! Finance",NA,
    "Online Interview","Stock Market Discussion","6ABC.com, Philadelphia ABC Affilitate website",NA,
    "Online Interview","Stock Market Discussion","NYTimes.com, New York Times Newspaper website",NA
)


bizExperiences <- tribble(
    ~title, ~company, ~begYear, ~endYear,
    "Independent Financial Consultant","BFCG, LLC and BFCG OU","2006","Present",
    "Investment Committee Advisory Board","Locust Capital Management","2011","2016",
    "Chief Modeling Officer","MutualDecision.com","2007","2009",
    "Senior Consultant","The Center for Forensic Economic Studies","2004","2006",
    "Forensic Economist","Tinari Economics","1997","2003",
    "Consultant","Financial Risk Consutling Group","2001","2003",
    "Financial Analyst","National Planning Corporation","1991","1992",
    "Laboratory Manager","Environmental Protection Systems","1986","1990",
    "Environmental Chemist","Toxicon Laboratories","1985","1986"
)

references <- tribble(
    ~name, ~title, ~details,
    
    "Bruce Weber",
    "Willem Kooyker Dean of the Zicklin School of Business",
    "55 Lexington Ave at 24th Street
    New York, NY 10010; 
    +1 646-312-1000;
    bruce.weber@baruch.cuny.edu",

    "Neil Pearson",
    "Professor, University of Illinois",
    "419 Wohlers Hall
    1206 S. Sixth
    Champaign, IL 61820; 
    +1 217-244-0490; 
    pearson2@illinois.edu",

    "Gene Pilotte",
    "Area Head and Professor of Finance",
    "Rutgers School of Business - Camden
    227 Penn Street, BSB 317, 
    Camden, NJ 08102; 
    +1 856-225-6548; 
    pilotte@camden.rutgers.edu",
    
    "Paul Brockman",
    "Joseph R. Perella and Amy M. Perella Chair
    Perella Department of Finance and Senior Associate Dean for Faculty and Research, 
    Lehigh University", 
    "Rauch Business Center 103, 
    621 Taylor Street
    Bethlehem, PA 18015; 
    +1 610-758-2914; 
    pab309@lehigh.edu",

    "Chitru Fernando",
    "Rainbolt Chair in Finance, Professor of Finance, Director of the Division of Finance and Director of the Center for Financial Studies,
    University of Oklahoma",
    "Adams Hall, Room 3264,
    307 W. Brooks,
    Norman, OK, 73019;
    +(405) 325-2906; 
    cfernando@ou.edu"
)
    
    

